### ISSUE TITLE
Player info struct is not correct for older demos.

### ISSUE THREAD

**Issue by taylorfinnell** [kaimallea/demoinfogo-linux#24]
On some demos the `deathscsv` command produces output like. 

`, ,<weapon>, <headshot>`

Instead of the expected

`<attacker_name>, <victim_name>, <weapon>, <headshot>`

A demo file that presents this issue is found in #21. This is due to the format of `player_info_t` changing. Luckily, it looks like that struct is meant to be versioned. The `player_info_t` that works for the demo file in #21 looks like this

```
struct player_info_t
{
    // version for future compatibility
    uint32          version;
    // network xuid
    uint32          xuid;
    // scoreboard information
    char            name[ 32 ];
        ...  <the rest is the same, I think> ...
```

Note: this is many bytes shorter than the currently defined `player_info_t`

The first 4 bytes of player_info_t seems to always be a version. The rest of the structure changes depending on that version. The parsing code should be updated to act differently on different versions and should raise an error when an unknown version is encountered.

**Comment by taylorfinnell** [comment]
Actually not so sure if that is a `version` for `GOTV` player it always seems to be 0...hmm, I wonder if we could use the `network protocol` version from the header or something instead

**Comment by moritzuehling** [comment]
You can use that as a switch, yes. It's basically the version number of CS:GO.

**Comment by kaimallea** [comment]
So the only difference between demo version is `player_info_t` uses `uint32` in the older demos and `uint46` presently?

**Comment by taylorfinnell** [comment]
@kaimallea The character array for the name is also sized differently.

@moritzuehling So it's always safe to use the first 4 bytes as a version number? It's been a few months since I have looked at any of this but I seem to remember getting some strange numbers. Also if some of the versions are 8 bytes (https://github.com/csgo-data/demoinfogo-linux/blob/552a2b3170ac5ab68bc6e049ef0dc0816f9543b0/src/demofiledump.h#L66) and some are 4 bytes it seems like that could be a point of issue?

**Comment by kaimallea** [comment]
@taylorfinnell ah, I see -- `MAX_PLAYER_NAME_LENGTH` is now `128`. Next question is ofc about the version numbers. I'll wait on @moritzuehling response :smiley:
